apiVersion: apps/v1
kind: Deployment
metadata:
  name: revorus-postgres
  labels:
    app: revorus-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revorus-postgres
  template:
    metadata:
      labels:
        app: revorus-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: revorus-escrow-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: revorus-escrow-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: revorus-escrow-secrets
              key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: revorus-postgres-svc
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: revorus-postgres
