apiVersion: apps/v1
kind: Deployment
metadata:
  name: revorus-redis
  labels:
    app: revorus-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revorus-redis
  template:
    metadata:
      labels:
        app: revorus-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        command: ["redis-server", "--appendonly", "yes"]
---
apiVersion: v1
kind: Service
metadata:
  name: revorus-redis-svc
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: revorus-redis
